---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    provisioner:
      sudo_command: sudo -H -E
  - name: centos-6.4
    provisioner:
      sudo_command: sudo -H -E

suites:
  - name: default
    run_list:
      - recipe[ctk-api::default]
    attributes:
